# Generated by Django 2.2.3 on 2019-08-22 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capchine', '0006_rating_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_code',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search_code',
            name='accessed_by',
            field=models.ManyToManyField(blank=True, related_name='accessed_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
