# Generated by Django 2.2.3 on 2019-08-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capchine', '0011_rating_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rated',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
