# Generated by Django 2.2.3 on 2019-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capchine', '0012_auto_20190822_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
