# Generated by Django 2.2.3 on 2019-08-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capchine', '0013_teacher_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_code',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
