# Generated by Django 2.2.3 on 2019-08-23 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capchine', '0014_search_code_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_code',
            name='accessed_byy',
            field=models.ManyToManyField(blank=True, null=True, related_name='accessed_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
